version: '3.3'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017

  mongo-seed:
    build: .
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    volumes:
      - ./config/db-seed:/data
    depends_on:
      - mongo
    command: [
      "mongoimport --host mongo --port 27017 --db mongo-seed --mode upsert --type json --file /data/user.json --jsonArray"
    ]
